// POST
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_POST = 'VOTE_POST';

// CATEGORY
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';

// COMMENT
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_POST_COMMENTS_COUNT = 'FETCH_POST_COMMENTS_COUNT';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_COMMENT_POST = 'FETCH_COMMENT_POST';
export const CREATE_COMMENT_POST = 'CREATE_COMMENT_POST';
export const EDIT_COMMENT_POST = 'EDIT_COMMENT_POST';
export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST';
export const VOTE_COMMENT = 'VOTE_COMMENT';
