// POST
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const VOTE_POST = 'VOTE_POST';

// POSTS
export const GET_POSTS_BY_CATEGORY_SUCCESS = 'GET_POSTS_BY_CATEGORY_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const UPVOTE_TO_POST = 'UPVOTE_TO_POST';
export const UPVOTE_TO_POST_SUCCESS = 'UPVOTE_TO_POST_SUCCESS';
export const DOWNVOTE_TO_POST = 'DOWNVOTE_TO_POST';
export const DOWNVOTE_TO_POST_SUCCESS = 'DOWNVOTE_TO_POST_SUCCESS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const EDIT_POST_BY_POST_ID = 'EDIT_POST_BY_POST_ID';

// CATEGORY
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';

// COMMENT
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_POST_COMMENTS_COUNT = 'FETCH_POST_COMMENTS_COUNT';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_COMMENT_POST = 'FETCH_COMMENT_POST';
export const CREATE_COMMENT_POST = 'CREATE_COMMENT_POST';
export const EDIT_COMMENT_POST = 'EDIT_COMMENT_POST';
export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST';
export const VOTE_COMMENT = 'VOTE_COMMENT';
